- name: Check if VirtualBox installed
  ansible.builtin.command: virtualbox --version
  register: virtualbox_check
  failed_when: false
  changed_when: false

- name: Install VirtualBox
  when: virtualbox_check.rc != 0
  become: true
  block:
    - name: Add VirtualBox deb822 repository
      ansible.builtin.deb822_repository:
        name: virtualbox
        types: deb
        uris: https://download.virtualbox.org/virtualbox/debian
        suites: "{{ ansible_facts['distribution_release'] }}"
        components: contrib
        architectures: amd64
        signed_by: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    - name: Install VirtualBox
      ansible.builtin.apt:
        name: virtualbox-7.1
        state: present
        update_cache: true

- name: Unload kvms
  ansible.builtin.command: sudo modprobe -r kvm_intel kvm_amd kvm

- name: Blacklist kvms
  ansible.builtin.copy:
    src: blacklist-kvm
    dest: /etc/modprobe.d/blacklist-kvm.conf
    mode: '440'
  become: true