- name: iot
  hosts: vm
  roles:
    # General
    - users
    - common
    - project
    # p1 & p2
    - vagrant
    - virtualbox
    # p3
    - role: geerlingguy.docker  # Docker
      become: true
    - role: averagebit.k3d      # K3d
      become: true
    # bonus
    - helm
  post_tasks:
    - name: Add user to groups
      become: true
      ansible.builtin.user:
        name: "nlam"
        groups:
          - docker
          - vboxusers
        append: true