- name: Setup p3
  hosts: all
  vars:
    - k3d_version: 5.9.0

  pre_tasks:
    - name: Install dependencies
      ansible.builtin.apt:
      name: kubectl
      update_cache: true
      state: present
  
  roles:
    - geerlingguy.docker
    - role: averagebit.k3d
      become: true
    - argocd
  
  tasks:

    - name: Create k3d cluster
      # https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/command_module.html
      ansible.builtin.command: k3d cluster create p3

    - name: Create dev namespace
      kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: dev

    - name: Copy application manifest
      ansible.builtin.copy:
        src: "application.yml"
        dest: "~/application.yml"
        owner: vagrant
        group: vagrant
        mode: '0644'

    - name: Create application
      # https://docs.ansible.com/projects/ansible/latest/collections/kubernetes/core/k8s_module.html
      kubernetes.core.k8s:
        state: present
        src: "~/application.yml"