# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant configuration
Vagrant.configure("2") do |config|

	# Global configurations (applied across all machines)
	config.vm.box = "generic/debian12"
	config.vm.box_version = "4.3.12"
	config.vm.provider "libvirt" do |lv|
		lv.cpus = 1
		lv.memory = 1024
	end

	# Server Machine
	config.vm.define "nlamS" do |server|
		server.vm.hostname = "nlamS"
		server.vm.network "private_network", ip: "192.168.56.110"
		server.vm.provision "ansible" do |ansible|
			ansible.playbook = "p2.yml"
			ansible.limit = "all"
			ansible.groups = {
				"server" => ["server"]
			}
		end
	end

end
