# -*- mode: ruby -*-
# vi: set ft=ruby :

SERVER		= "nlamS"
SERVER_IP	= "192.168.56.110"
K3S_VERS	= "v1.31.4+k3s1"

# Vagrant configuration
Vagrant.configure("2") do |config|

	# Global configurations (applied across all machines)
	config.vm.box = "bento/debian-12"
	config.vm.provider "virtualbox" do |vb|
		vb.cpus = 1
		vb.memory = 1024
	end

	# Server Machine
	config.vm.define SERVER do |server|
		server.vm.hostname = SERVER
		server.vm.network "private_network", ip: SERVER_IP
		#Provision via Shell
		server.vm.provision "file", source: "configs", destination: "$HOME/configs"
		server.vm.provision "shell", path: "scripts/server.sh"
		server.vm.provision "shell", path: "scripts/launch.sh"
		# Provision via Ansible
		#server.vm.provision "ansible" do |ansible|
		#	ansible.playbook = "p2.yml"
		#	ansible.limit = "all"
		#	ansible.groups = {
		#		"k3s_cluster" => [SERVER],
		#		"server" => [SERVER]
		#	}
		#	ansible.extra_vars = {
		#		k3s_version: K3S_VERS,
		#		api_endpoint: SERVER_IP
		#	}
		#end
	end

end
