# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant configuration
Vagrant.configure("2") do |config|

	# Global configurations (applied across all machines)
	config.vm.box = "bento/ubuntu-24.04"
	config.vm.provider "vmware_desktop" do |vmw|
		vmw.vmx["numvcpus"] = "1"
		vmw.vmx["memsize"] = "1024"
		vmw.gui = false
	end

	# Server Machine
	config.vm.define "nlamS" do |server|
		server.vm.hostname = "nlamS"
		server.vm.network "private_network", ip: "192.168.56.110"
		server.vm.provision "shell", path: "scripts/server.sh"
	end

end