# -*- mode: ruby -*-
# vi: set ft=ruby :

# Ensure shared folder exists and is empty
require 'fileutils'
FileUtils.rm_rf('.shared')
FileUtils.mkdir_p('.shared')

# Vagrant configuration
Vagrant.configure("2") do |config|

	# Global configurations (applied across all machines)
	config.vm.box = "bento/debian-12"
	config.vm.provider "libvirt" do |lv|
		lv.cpus = 1
		lv.memory = 1024
		lv.gui = true
	end

	# Machine 1: Server
	config.vm.define "nlamS" do |server|
		server.vm.hostname = "nlamS"
		server.vm.network "private_network", ip: "192.168.56.110"
	end

	# Machine 2: Server Worker
	config.vm.define "nlamSW" do |agent|
		agent.vm.hostname = "nlamSW"
		agent.vm.network "private_network", ip: "192.168.56.111"
		# agent.vm.provision "file", 
      	# 	source: ".vagrant/machines/nlamS/libvirt/private_key",
      	# 	destination: "/home/vagrant/key.txt"
	end

end
