# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant configuration
Vagrant.configure("2") do |config|

	# Global configurations (applied across all machines)
	config.vm.box = "generic/debian12"
	config.vm.box_version = "4.3.12"
	config.vm.provider "libvirt" do |lv|
		lv.cpus = 1
		lv.memory = 1024
	end

	# Machine 1: Server
	config.vm.define "nlamS" do |server|
		server.vm.hostname = "nlamS"
		server.vm.network "private_network", ip: "192.168.56.110"
	end

	# Machine 2: Server Worker
	config.vm.define "nlamSW" do |agent|
		agent.vm.hostname = "nlamSW"
		agent.vm.network "private_network", ip: "192.168.56.111"
	end

	# Provisioning via Ansible
	# https://github.com/k3s-io/k3s-ansible
		agent.vm.provision "ansible" do |ansible|
		ansible.playbook = "p1.yml"
		ansible.limit = "all"
		ansible.groups = {
			"server" => ["server"],
			"agent" => ["agent"]
		}
	end
end
