apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bonus-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/panache/nlam-iot.git
    targetRevision: HEAD
    path: .
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
