# gitlab-values.yml

global:
  edition: ce

certmanager-issuer:
  email: nlam@42.fr

# Disable components you probably don't need
prometheus:
  install: false

gitlab-runner:
  install: false

registry:
  enabled: false

nginx-ingress:
  enabled: true

certmanager:
  prometheus:
    enabled: false

# Keep GitLab components small
gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 2Gi

  sidekiq:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi

  gitaly:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
