global:
  hosts:
    domain: localhost
    gitlab:
      name: localhost
    minio:
      name: minio.localhost
    https: false
  ingress:
    configureCertmanager: false
    class: "traefik"
    tls:
      enabled: false
  rails:
    bootsnap:
      enabled: false
  pages:
    enabled: false

nginx-ingress:
  enabled: false
prometheus:
  install: false
registry:
  enabled: false
gitlab-runner:
  install: false

redis:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
minio:
  resources:
    requests:
      memory: 64Mi
      cpu: 10m

gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 1G
      limits:
        memory: 2G
    workhorse:
      resources:
        requests:
          cpu: 10m
          memory: 10M
        limits:
          memory: 100M
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 750M
      limits:
        memory: 1.5G
  gitaly:
    resources:
      requests:
        cpu: 100m
        memory: 300Mi
      limits:
        memory: 600Mi
  redis:
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 256Mi
  minio:
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 256Mi
  gitlab-shell:
    enabled: false
  toolbox:
    enabled: false
  praefect:
    enabled: false
  kas:
    enabled: false  # kubernetes agent server
  spamcheck:
    enabled: false  # spam checking service
