# -*- mode: ruby -*-
# vi: set ft=ruby :

# Ensure shared folder exists
require 'fileutils'
FileUtils.mkdir_p '.shared'

Vagrant.configure("2") do |config|

	# Global configurations (applied across all machines)
	config.vm.box = "bento/ubuntu-24.04"
	config.vm.synced_folder ".shared", "/vagrant_shared"
	config.vm.provider "vmware_desktop" do |vmw|
		vmw.vmx["numvcpus"] = "1"
		vmw.vmx["memsize"] = "512"
		vmw.gui = false
	end

	# Machine 1: Server
	config.vm.define "nlamS" do |server|
		server.vm.hostname = "nlamS"
		server.vm.network "private_network", ip: "192.168.56.110"
		server.vm.provision "shell", path: "./scripts/server.sh"
	end

	# Machine 2: Server Worker
	config.vm.define "nlamSW" do |agent|
		agent.vm.hostname = "nlamSW"
		agent.vm.network "private_network", ip: "192.168.56.111"
		# Wait until the server's token file exists before provisioning
		agent.vm.provision "shell", inline: <<-SHELL
			echo "Waiting for server token file..."
			while [ ! -f /vagrant_shared/token ]; do
				sleep 3
				echo "Still waiting..."
			done
			echo "Token found! Starting K3s agent setup."
		SHELL
		agent.vm.provision "shell", path: "./scripts/agent.sh"
	end

end