# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'securerandom'

Vagrant.configure("2") do |config|

	config.vm.box = "generic/debian12"
	config.vm.box_version = "4.3.12"

	# Global provider configuration (applies to all machines)
	config.vm.provider "virtualbox" do |vb|
		vb.cpus = 1
		vb.memory = 512
		vb.gui = false
	end

	# Generate random K3S_TOKEN
	token_file = "k3s_token.txt"
	token = File.exist?(token_file) ? File.read(token_file).strip : SecureRandom.hex(16)
	File.write(token_file, token) unless File.exist?(token_file)

	# Machine 1: Server
	config.vm.define "nlamS" do |server|
		server.vm.hostname = "nlamS"
		server.vm.network "private_network", ip: "192.168.56.110"
		server.vm.provision "shell", inline: <<-SHELL
			snap remove curl
			apt update -
			apt install -y curl
			curl -sfL \
				https://get.k3s.io | \
				K3S_TOKEN=#{token} \
				sh -
		SHELL
	end

	# Machine 2: Server Worker
	config.vm.define "nlamSW" do |agent|
		agent.vm.hostname = "nlamSW"
		agent.vm.network "private_network", ip: "192.168.56.111"
		agent.vm.provision "shell", inline: <<-SHELL
			snap remove curl	
			apt update -y
			apt install -y curl
			curl -sfL \
				https://get.k3s.io | \
				K3S_URL=https://192.168.56.110:6443 \
				K3S_TOKEN=#{token} \
				sh -
			# K3S_TOKEN is stored at /var/lib/rancher/k3s/server/node-token on server node
		SHELL
	end

end
